### ISSUE TITLE
Failed to fetch plugin cordova-wheel-selector-plugin via registry

### ISSUE THREAD

**Issue by henkverschoor1994** [jasonmamy/cordova-wheel-selector-plugin#8]
When I try install the plugin, with this command: 
`ionic cordova plugin add cordova-wheel-selector-plugin`

I got the following error:
```
> cordova plugin add cordova-wheel-selector-plugin --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add cordova-wheel-selector-plugin --save (exit code 1):

        Error: Failed to fetch plugin cordova-wheel-selector-plugin via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 4294963248 Error output:
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
        npm ERR! path C:\Apps\vfa\vfa\node_modules\.staging\cordova-wheel-selector-plugin-41818eae
        npm ERR! code EPERM
        npm ERR! errno -4048
        npm ERR! syscall rename
        npm ERR! Error: EPERM: operation not permitted, rename 'C:\Apps\vfa\vfa\node_modules\.staging\cordova-wheel-selector-plugin-41818eae' -> 'C:\Apps\vfa\vfa\node_modules\cordova-wheel-select
or-plugin'
        npm ERR!     at Error (native)
        npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Apps\vfa\vfa\node_modules\.staging\cordova-wheel-selector-plugin-41818eae' -> 'C:\Apps\vfa\vfa\node_modules\cordova-wheel-sel
ector-plugin'
        npm ERR!     at Error (native)
        npm ERR!   errno: -4048,
        npm ERR!   code: 'EPERM',
        npm ERR!   syscall: 'rename',
        npm ERR!   path: 'C:\\Apps\\vfa\\vfa\\node_modules\\.staging\\cordova-wheel-selector-plugin-41818eae',
        npm ERR!   dest: 'C:\\Apps\\vfa\\vfa\\node_modules\\cordova-wheel-selector-plugin',
        npm ERR!   parent: 'ionic-hello-world' }
        npm ERR!
        npm ERR! Please try running this command again as root/Administrator.
```

I got the same error when I run it as Administrator.

I am working with Ionic2, and installing the plugin with NPM is okay, but then I got this error in the app: `Native: tried calling WheelSelector.show, but the WheelSelector plugin is not installed.`
So I need the cordova plugin, but how can I install it?

**Comment by henkverschoor1994** [comment]
Okay, new update. When I install it with a specified version, it works: 
Try this:  `ionic cordova plugin add cordova-wheel-selector-plugin@1.0.0`

Edit: Case can be closed, because I used the current version of NodeJS and not the LTS version of NodeJS (and NPM). I downgraded to the LTS version and it works

**Comment by jasonmamy** [comment]
In my config.xml I have:

<plugin name="cordova-wheel-selector-plugin" spec="~1.0.0" />

Look in your package.json and make sure there's no hard-coded version of
the wheel selector (that one got me once).


Here's what I have:


ionic cordova plugin add cordova-wheel-selector-plugin
ouput:
> cordova plugin add cordova-wheel-selector-plugin --save
✔ Running command - done!
Fetching plugin "cordova-wheel-selector-plugin@~1.0.0" via npm
Plugin "cordova-wheel-selector-plugin" already installed on android.
Plugin "cordova-wheel-selector-plugin" already installed on browser.
Saved plugin info for "cordova-wheel-selector-plugin" to config.xml


My ionic info (not sure what version you're running on):

ionic info

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.1
    OS         : Linux 3.16
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed


Since the wheel selector is not released yet in ionic-native (not sure when
they're planning on their next release), you have to do these steps for
ionic2 (maybe 5-10 min):

https://github.com/jasonmamy/cordova-wheel-selector-plugin#ionic-2

Which builds the wrapper, then just copy to your project and it should work
(I think that's the error that you're seeing when it says 'not installed'.
I built it for my project, then just checked in the built wrapper in the
root of my project, and as part of my build script just copy the dir over
to the node_modules directory to keep it easy for now.


Lemme know if this helps

**Comment by jasonmamy** [comment]
Fix, use this link for the ionic native build instructions:

https://github.com/jasonmamy/cordova-wheel-selector-plugin#for-ionic-2
